---

- name: create tmp download dir
  file: path=~/tmp state=directory

- name: download installer
  get_url: url=https://www.cs.uoregon.edu/research/tau/pdt_releases/pdt-3.20.tar.gz
           dest=~/tmp/pdt.tgz
           validate_certs=no
           #sha256sum=b4690319856f9a4cbb73cdd498d358666412d1fbc8848f1e83edf4d5d62d69fe

- name: extract package
  command: chdir=~/tmp/ tar -xf pdt.tgz
           creates=~/tmp/pdtoolkit-3.20

#- name: configure installation
#  command: chdir=~/tmp/tau-2.24 ./configure -prefix={{ install_dir }}/tau -openmp -pythoninc={{ install_dir }}/anaconda/include/python2.7 -pythonlib={{ install_dir }}/anaconda/lib/python2.7 -PROFILE -opari -opari_region -opari_construct -bfd=download
#           creates=~/tmp/parallel-20140322/Makefile
# -pdt=/opt/pdt -TRACE -LINUXTIMERS

#- name: install
#  command: chdir=~/tmp/tau-2.24 make install
#           creates={{ install_dir }}/tau

#- name: ensure modulefiles dir exists
#  file: path={{ install_dir }}/modulefiles state=directory

#- name: Configure modulefile
#  template: src=tau.lua.j2 dest={{ install_dir }}/modulefiles/tau.lua
