---

- name: create tmp download dir
  file: path=~/tmp state=directory

- name: download installer
  get_url: url={{ wgs_download_url }}
           dest=~/tmp/wgs-{{ wgs_version }}.tar.bz2
           sha256sum={{ wgs_download_sha256 }}

- name: extract package
  command: chdir=~/tmp/ tar -xf wgs-{{ wgs_version }}.tar.bz2
           creates=~/tmp/wgs-{{ wgs_version }}

- name: ensure module dir exists
  file: path={{ install_dir }}/wgs-assembler/{{ wgs_version }} state=directory

- name: install
  command: chdir=~/tmp/wgs-{{ wgs_version }} cp -a Linux-amd64/ {{ install_dir }}/wgs-assembler/{{ wgs_version }}
           creates={{ install_dir }}/wgs-assembler/{{ wgs_version }}/Linux-amd64/bin

- name: ensure modulefiles dir exists
  file: path={{ install_dir }}/modulefiles/wgs-assembler state=directory

- name: Configure modulefile
  template: src=wgs-assembler.lua.j2 dest={{ install_dir }}/modulefiles/wgs-assembler/{{ wgs_version }}.lua
