---

- name: create tmp download dir
  file: path=~/tmp state=directory

- name: download freeglut source
  get_url: url=http://downloads.sourceforge.net/project/freeglut/freeglut/2.8.1/freeglut-2.8.1.tar.gz
           dest=~/tmp/freeglut-2.8.1.tar.gz
           #sha256sum=b4690319856f9a4cbb73cdd498d358666412d1fbc8848f1e83edf4d5d62d69fe

- name: extract freeglut source
  command: chdir=~/tmp/ tar -xf freeglut-2.8.1.tar.gz
           creates=~/tmp/freeglut-2.8.1

- name: configure freeglut installation
  command: chdir=~/tmp/freeglut-2.8.1 ./configure --prefix={{ install_dir }}/haskell-platform
#           creates=~/tmp/parallel-20140322/Makefile

- name: install freeglut
  command: chdir=~/tmp/freeglut-2.8.1 make install
           creates={{ install_dir }}/haskell-platform

- name: download installer
  get_url: url=http://www.haskell.org/platform/download/2013.2.0.0/haskell-platform-2013.2.0.0.tar.gz
           dest=~/tmp/haskell-platform-2013.2.0.0.tar.gz
           #sha256sum=b4690319856f9a4cbb73cdd498d358666412d1fbc8848f1e83edf4d5d62d69fe

- name: extract package
  command: chdir=~/tmp/ tar -xf haskell-platform-2013.2.0.0.tar.gz
           creates=~/tmp/haskell-platform-2013.2.0.0

- name: configure installation
  command: chdir=~/tmp/haskell-platform-2013.2.0.0 ./configure --prefix={{ install_dir }}/haskell-platform --with-ghc={{ install_dir }}/ghc/bin/ghc --with-ghc-pkg={{ install_dir }}/ghc/bin/ghc-pkg
  environment:
    CPPFLAGS: "-I /opt/software/ged-software/haskell-platform/include"
#           creates=~/tmp/parallel-20140322/Makefile

- name: install
  command: chdir=~/tmp/haskell-platform-2013.2.0.0 make install
           creates={{ install_dir }}/haskell-platform

- name: ensure modulefiles dir exists
  file: path={{ install_dir }}/modulefiles state=directory

- name: Configure modulefile
  template: src=haskell-platform.lua.j2 dest={{ install_dir }}/modulefiles/haskell-platform.lua
