---

- name: create tmp download dir
  file: path=~/tmp state=directory

- name: download installer
  get_url: url=https://releases.ansible.com/ansible/ansible-1.9.4.tar.gz
           dest=~/tmp/ansible-1.9.4.tar.gz
           #sha256sum={{ sha256sum }}

- name: extract package
  command: chdir=~/tmp/ tar -xf ansible-1.9.4.tar.gz
           creates=~/tmp/ansible-1.9.4

- name: copy to the install dir
  command: cp -r ~/tmp/ansible-1.9.4 {{ install_dir }}/ansible
           creates={{ install_dir }}/ansible

#  command: chdir=~/tmp/ansible-1.5.4./configure --prefix={{ install_dir }}/parallel
#           creates=~/tmp/parallel-20140322/Makefile

#- name: install
#  command: chdir=~/tmp/parallel-20140322 make install
#           creates={{ install_dir }}/parallel

- name: ensure modulefiles dir exists
  file: path={{ install_dir}}/modulefiles state=directory

- name: Configure modulefile
  template: src=ansible.lua.j2 dest={{ install_dir}}/modulefiles/ansible.lua
