---

- name: create tmp download dir
  file: path=~/tmp state=directory

- name: download installer
  get_url: url=http://09c8d0b2229f813c1b93-c95ac804525aac4b6dba79b00b39d1d3.r79.cf1.rackcdn.com/Anaconda-1.9.2-Linux-x86_64.sh
           dest=~/tmp/Anaconda-1.9.2-Linux-x86_64.sh
           sha256sum=7181d399833a2549a9584255bb477487f2fde1fda4c7f7215d6034ea2fcfa21e

- name: execute installer
  command: chdir=~/tmp/ bash Anaconda-1.9.2-Linux-x86_64.sh -b -p {{ install_dir }}/anaconda
           creates={{ install_dir}}/anaconda

- name: ensure modulefiles dir exists
  file: path={{ install_dir }}/modulefiles state=directory

- name: Configure modulefile
  template: src=anaconda.lua.j2 dest={{ install_dir}}/modulefiles/anaconda.lua
